displayName=Chronicle
author=Fitzgerald
description=A comprehensive journal of your OSRS account.
tags=journal,stats,tracker,loot,slayer,collection,osrs
version=1.0
plugins=chronicle.ChroniclePlugin
build=standard
