initscript {
	repositories {
		gradlePluginPortal()
	}
	dependencies {
		classpath 'com.github.spotbugs.snom:spotbugs-gradle-plugin:5.2.5'
	}
}

allprojects {
	apply plugin: com.github.spotbugs.snom.SpotBugsPlugin
	spotbugs {
		effort = 'max'
		reportLevel = 'medium'
		excludeFilter = file('config/spotbugs-exclude.xml')
	}
	tasks.matching { it.name == 'spotbugsTest' }.configureEach {
		enabled = false
	}
}
